# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

chart_groups:
  - name: docker_registry
    timeout: 600
    charts:
      - docker_registry_nfs_provisioner
      - docker_registry_redis
      - docker_registry

  - name: infra_monitoring
    timeout: 600
    charts:
      - prometheus
      - nagios
      - prometheus_node_exporter
      - prometheus_kube_state_metrics
      - prometheus_alertmanager
      - grafana

  - name: openstack_infra_exporters
    timeout: 600
    charts:
      - prometheus_openstack_exporter

  - name: openstack_infra_logging
    timeout: 1200
    charts:
      - openstack_elasticsearch
      - fluent_logging
      - kibana

charts:
  docker_registry_nfs_provisioner:
    chart_name: nfs-provisioner
    release: docker-registry-nfs-provisioner
    namespace: docker-registry
    upgrade:
      pre:
        delete:
          - name: docker-bootstrap
            type: job
            labels:
              application: docker
              component: bootstrap
    values:
      labels:
        node_selector_key: openstack-helm-node-class
        node_selector_value: primary
      storageclass:
        name: openstack-helm-bootstrap

  docker_registry_redis:
    chart_name: redis
    release: docker-registry-redis
    namespace: docker-registry
    values:
      labels:
        node_selector_key: openstack-helm-node-class
        node_selector_value: primary

  docker_registry:
    chart_name: registry
    release: docker-registry
    namespace: docker-registry
    values:
      labels:
        node_selector_key: openstack-helm-node-class
        node_selector_value: primary
      volume:
        class_name: openstack-helm-bootstrap

  prometheus:
    chart_name: prometheus
    release: prometheus
    namespace: openstack
    timeout: 300
    test:
      enabled: true
      timeout: 300
      output: false
    values:
      storage:
        enabled: false
      manifests:
        pvc: false
      network:
        prometheus:
          ingress:
            public: false

  prometheus_kube_state_metrics:
    chart_name: prometheus-kube-state-metrics
    release: prometheus-kube-metrics
    namespace: kube-system
    test:
      enabled: false
      timeout: 300
      output: false

  prometheus_node_exporter:
    chart_name: prometheus-node-exporter
    release: prometheus-node-exporter
    namespace: kube-system
    test:
      enabled: false
      timeout: 300
      output: false

  prometheus_alertmanager:
    chart_name: prometheus-alertmanager
    release: prometheus-alertmanager
    namespace: openstack
    test:
      enabled: false
      timeout: 300
      output: false
    values:
      storage:
        enabled: false
      manifests:
        pvc: false
      network:
        alertmanager:
          ingress:
            public: false

  nagios:
    chart_name: nagios
    release: nagios
    namespace: openstack
    values:
      network:
        nagios:
          ingress:
            public: false

  prometheus_openstack_exporter:
    chart_name: prometheus-openstack-exporter
    release: prometheus-openstack-exporter
    namespace: openstack
    timeout: 300
    test:
      enabled: false
      timeout: 300
      output: false
    values:
      # NOTE(portdirect): Keystone Management is disabled here, as keystone is
      # not deployed in the OSH infra gates.
      manifests:
        job_ks_user: false
      dependencies:
        static:
          prometheus_openstack_exporter:
            jobs: null
            services: null

  grafana:
    chart_name: grafana
    release: prometheus-grafana
    namespace: openstack
    test:
      enabled: false
      timeout: 300
      output: false
    values:
      dependencies:
        static:
          grafana:
            jobs: null
            services: null
      manifests:
        ingress: false
        job_db_init: false
        job_db_init_session: false
        job_db_session_sync: false
        secret_db: false
        secret_db_session: false
        service_ingress: false
      conf:
        grafana:
          database:
            type: sqlite3
          session:
            provider: file
            provider_config: sessions
      network:
        grafana:
          ingress:
            public: false

  openstack_elasticsearch:
    chart_name: elasticsearch
    release: elasticsearch
    namespace: openstack
    timeout: 600
    test:
      enabled: true
      timeout: 600
      output: false
    values:
      storage:
        elasticsearch:
          storage_class: openstack-helm-bootstrap
        filesystem_repository:
          storage_class: openstack-helm-bootstrap
      monitoring:
        prometheus:
          enabled: true

  fluent_logging:
    chart_name: fluent-logging
    release: fluent-logging
    namespace: openstack
    timeout: 600
    test:
      enabled: true
      timeout: 600
      output: false
    values:
      monitoring:
        prometheus:
          enabled: true


  kibana:
    chart_name: kibana
    release: kibana
    namespace: openstack
